### ISSUE TITLE
server/modules/searchscrape.js triggering error with cheerio.

### ISSUE THREAD

**Issue by jrjgh** [all-american-regex/all-american-regex#1]
I don't know whether the error is in searchscrape.js, or if cheerio needs to be updated. Error is below.

/Users/jj/Documents/MakerSquare/Greenfield/all-american-regex/node_modules/cheerio/lib/parse.js:55
    var oldParent = node.parent || node.root,
                        ^

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/Users/jj/Documents/MakerSquare/Greenfield/all-american-regex/node_modules/cheerio/lib/parse.js:55:25)
    at module.exports (/Users/jj/Documents/MakerSquare/Greenfield/all-american-regex/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (/Users/jj/Documents/MakerSquare/Greenfield/all-american-regex/node_modules/cheerio/lib/static.js:19:14)
    at extractResults (/Users/jj/Documents/MakerSquare/Greenfield/all-american-regex/server/modules/searchscrape.js:76:21)
    at onPage (/Users/jj/Documents/MakerSquare/Greenfield/all-american-regex/server/modules/searchscrape.js:15:26)
    at Request._callback (/Users/jj/Documents/MakerSquare/Greenfield/all-american-regex/server/modules/searchscrape.js:55:20)
    at Request.self.callback (/Users/jj/Documents/MakerSquare/Greenfield/all-american-regex/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/jj/Documents/MakerSquare/Greenfield/all-american-regex/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/jj/Documents/MakerSquare/Greenfield/all-american-regex/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)

**Comment by hhoughgg** [comment]
I'm going to mess around with it now. I changed a ton of stuff with the scraper yesterday so it's a bit buggy.

**Comment by hhoughgg** [comment]
Unfortunately our teammates went on a boat. Boats are very dangerous so it's probably just me and you from here on out.

**Comment by jrjgh** [comment]
Works now.
